### ISSUE TITLE
not able to post comments

### ISSUE THREAD

**Issue by Tadies** [TwoBeers/shiword#11]
hello guys..
im not bale to post acomment on shiword page on ur end..
getting password error......
what i wanted to ask is >>

hi guys! is there a simple css way to make the sidebar a bit smaller and that the post or page content is getting the extra space?
without modufieing the whole layout zise?

is this possible by a simply css that i can put in on custom.css?
thanks!

**Comment by ilmaren** [comment]
Hi Tadies,
sorry for the long time, but we're on holiday :).

About your first question, password error, there was a problem with spam free plugin, now solved (thanks to your report :-) )

There's not a simple way to mod the size, but you can add customize css directly from _Dashboard -> Appearance -> Theme Options_: you'll find "custom CSS code" under More section.

Hope it helps

**Comment by Tadies** [comment]
thank you very much Ilmaren!
i was indeed playing around with the custom css
also im able to set the sidebar on the zise i wanted,
but im  failing on the content area..
to assign that extra space..
but thanks though!  keep rocking....

**Comment by ilmaren** [comment]
Maybe this tutorial can help you:
http://www.twobeers.net/guide/how-to-use-firebug-to-learnedit-css-code

**Comment by ilmaren** [comment]
The css class of the content area (when sidebar is active), is .posts_narrow, otherwise .posts_wide

**Comment by Tadies** [comment]
thank you! :)
