### ISSUE TITLE
UPDATE/TWEAK site to run faster with wordpress 3.5

### ISSUE THREAD

**Issue by fibercarbon** [TwoBeers/shiword#12]
i love version: 3.04 shiword i have been using it for a year now, just curious if you plan on updating the javascripts and coding to tweak and make the site load faster? Keep up the Great work!!

**Comment by ilmaren** [comment]
Hi fibercarbon,
sorry for the late reply.
We're working on a new release of shiword.
Hope it'll satisfy your needs
