### ISSUE TITLE
Warning: preg_replace() [function.preg-replace]: Compilation failed: nothing to repeat at offse

### ISSUE THREAD

**Issue by LuxMagesh** [TwoBeers/shiword#15]
Warning: preg_replace() [function.preg-replace]: Compilation failed: nothing to repeat at offset 2 in /home/sluggdch/public_html/wp-content/plugins/tag-search/tt-tag-search.php on line 172

**Comment by LuxMagesh** [comment]
Hi Guys 

Ive managed to mess up my site with stupid post pls help

**Comment by ilmaren** [comment]
Hi Lux,
the problem is related to tag-search/tt-tag-search.php, not with the theme.
You should deactivate that plugin or ask for help to the plugin author.
