### ISSUE TITLE
Top of page icon gone

### ISSUE THREAD

**Issue by briangladstone** [TwoBeers/shiword#18]
Greetings  ... im using shiwood .. it is a great theme and works well
the top of page icon disappeared .. can you help to get it back?
www.briangladstone.ca 
Thanks

**Comment by ilmaren** [comment]
Hi Brian,
there's a js error in shane-web-guy-portfolio plugin (as you can see from the screenshot attached), this can block shiword's js execution. Try disable the plugin and report the problem to the plugin author if you need it.

![screenshot-3](https://f.cloud.github.com/assets/436811/243044/9bcaec1c-8a36-11e2-8cd4-25e482b62b5a.jpg)

**Comment by ilmaren** [comment]
shane-web-guy-portfolio plugin has been removed from site and issue is solved.
BTW, no reply --> closed
