### ISSUE TITLE
Smooth Slider Issue

### ISSUE THREAD

**Issue by ClarisaClarity** [TwoBeers/shiword#19]
Hi,

First, thanks for the theme. It's quite handy, with a good amount of features, without sacrificing flexibility. Very well done.

I'm currently running two instances of Shiword.The first is in my MAMP, where I experiment, and the second on a live site. On both instances I'm using the SmoothSlider Plugin. (http://www.clickonf5.org/smooth-slider/)

The plugin works brilliantly in the MAMP version of the theme which is identical, as far as I can tell, to the live version. But, the live version gives me this message above the plugin anywhere I instal it:

Warning: Missing argument 2 for shiword_title_tags_filter() in /homepages/31/d121987168/htdocs/ChrisClubWordPress/ChrisClubWordPress/wp-content/themes/shiword/functions.php on line 1347

I've already copied the functions php directly from the MAMP to the live site to guarantee that they are the same. 

Thoughts?

Best,
Clarisa

**Comment by ilmaren** [comment]
Hi Clarisa,
thank for the good words on our theme (if you have time, a feedback on our main site will be very appreciated http://www.twobeers.net/annunci/shiword).

A link to the site would be really usefull in this case.
BTW I think you can temporary solve the problem by disabling debug on the live site (a warning is nothing serious and I think - but I'm not sure - it's related to an empty title - shiword function that handle empty titles has been improve in the next release - you can try it out by downloading the beta from here https://github.com/TwoBeers/shiword/archive/master.zip - beware it's a beta).
