### ISSUE TITLE
v3.04 problem with Opera Browser

### ISSUE THREAD

**Issue by MelodicRainer** [TwoBeers/shiword#21]
Every time I scroll page, it happened like this <a href="http://s658.photobucket.com/user/aisck811110/media/ShiwordproblemwithOpera_zpsedd0e0ca.png.html" target="_blank"><img src="http://i658.photobucket.com/albums/uu304/aisck811110/ShiwordproblemwithOpera_zpsedd0e0ca.png" border="0" alt=" photo ShiwordproblemwithOpera_zpsedd0e0ca.png"/></a>

Even if cursor above on the icon, the animation won't show up.<a href="http://s658.photobucket.com/user/aisck811110/media/Shiwordproblemicon_zps145c278d.png.html" target="_blank"><img src="http://i658.photobucket.com/albums/uu304/aisck811110/Shiwordproblemicon_zps145c278d.png" border="0" alt=" photo Shiwordproblemicon_zps145c278d.png"/></a>

**Comment by ilmaren** [comment]
Hi MelodicRainer,
many thanks for your submission.
This is a browser compatibility issue and I'm afraid I'm not able to help you right now.
You should wait untill next week for Jimo to be back.
Thank again, bye

**Comment by MelodicRainer** [comment]
Thanks for comment.

I'll be waiting for update of Opera.

**Comment by jimo** [comment]
this strange issue has a strange solution...
just set the z-index property of #navbuttons div to some high value (eg 99) and everything works fine :tada:
