### ISSUE TITLE
I'm a coding moron: how do I upgrade Shiword?

### ISSUE THREAD

**Issue by steadystate** [TwoBeers/shiword#24]
Hi,

  Finally got around to updating my site tonight (Wordpress, Shiword theme).  I encountered the 'Fatal error: Cannot redeclare class Custom_Background, etc, line 16' error, and have found a few suggested solutions.  Seems the most effective is just to update Shiword as well, so I've downloaded the latest update, but don't know what to do next.  Update some files via ftp?  I have a webmaster for this purpose but he's in China for the next three weeks, and in the meantime I've broken my website by trying to do something on my own.

  I'm technologically inept, I'm afraid.  Help?

cheers,
Jason

**Comment by ilmaren** [comment]
Hi Jason,
sorry for the long it takes, but I had connection problem and I've been outoftheworld for several days.

To fix the problem you have to upload the new version of Shiword to your server through FTP or delete Shiword folder and install it again via "theme installer".

Both way require the same basic FTP knowledge, that is: connect to your server via FTP, open a couple of folder and delete one or upload a new one.
If you think you can do it I'll give you the instructions.

**Comment by jimo** [comment]
besides, if you delete the Shiword folder (via ftp), Wordpress should fallback to the default theme (TwentyTwelve, I suppose)

**Comment by ilmaren** [comment]
yep, I've forgot to mention that: it's a WP automatism, nothing to worry about.

**Comment by steadystate** [comment]
Thanks for the advice guys -- and I understand what you're saying, to either upload a new version or delete the old one, but this introduces a problem I encountered initially: I can't find a Shiword folder.  I've gone through every single folder and sub-folder in my FTP and there's not a single mention of Shiword anywhere.  My web designer might've named it something else but I have no clue, and there is zero about Shiword anywhere in there.  :\  So I know WHAT to do, just now how to find the right files to do it to!

**Comment by ilmaren** [comment]
In a standard WP installation themes should be under "wp-content\themes\" folder together with twenty-eleven and other themes. If there's not a wp-content\themes folder it's hard to help you without any clue. If there's one, but there's not shiword folder, just copy it through ftp (in some hosts configuration could happen that automatism fail)

Inviato da Android.

-----Original Message-----

**Comment by steadystate** [comment]
Thanks, guys.  I deleted the Shiword folder entirely initially and that, I guess obviously enough in retrospect, disabled my site entirely.  So then I uploaded the update, 3.04, and everything's working brilliantly again.  Thank you SO MUCH for your assistance.  You guys are great.  Really appreciate it!

**Comment by jimo** [comment]
There was a time when WP used to fall back to default theme if the current is unavailable... now it doesn't (guess why?)
Anyway I'm glad you solved the problem :)
