### ISSUE TITLE
Customizzazione, un aiuto :-)

### ISSUE THREAD

**Issue by Avelix71** [TwoBeers/shiword#28]
Buongiorno, avrei bisogno di sapere una cosa banale, alla quale non ho risposta poichè non ho modo di testare direttamente: il tema mantiene l'aspetto grafico e stilistico impostato per il lato desktop anche su dispositivi "mobile"? Lo chiedo perchè se abilito l'opzione "mobile" e dal mio PC provo a collegarmi, vedo che si perdono le slidebar, i menù a icone, lo slideshow...e mi visualizza solo una finestrella con l'ultimo articolo....
Grazie per la gentile risposta

**Comment by jimo** [comment]
Buongiorno a te, con l'ultima versione di Shiword è stata ottimizzata anche la compatibilità con gli schermi molto piccoli (con risoluzioni minori di 800px, ovvero i dispositivi mobili) senza per forza dover usare il tema "mobile". Quest'ultimo ha il vantaggio di essere molto leggero e quindi di poter essere caricato più velocemente, ma , come hai visto, si perdono alcune funzionalità. Faccio però notare che anche il tema mobile ha il suo menu (aspetto -> menu -> "Menu di Navigazione per mobile") e la sua sidebar (aspetto -> widget -> "Area Widget Mobile" ) che possono essere personalizzate.
Per avere un'idea di come potrebbe apparire il tuo sito sui dispositivi mobili, basta che rimpicciolisci la finestra del tuo browser
Spero di esserti stato d'aiuto

**Comment by jimo** [comment]
no reply -> closed
