### ISSUE TITLE
Youtube IFRAME Embed Player Problem WIth WP v3.5.2 and Shiword 4.0.3

### ISSUE THREAD

**Issue by glennherman** [TwoBeers/shiword#33]
Since upgrading to WP 3.5.2 I notice that the youtube embedded players do not display in the excerpt lists, but they do appear in the post itself. When I change the theme to twentytwelve, the youtube embeds do display properly in th excerpted listings..

**Comment by glennherman** [comment]
Please consider this issue as closed.

**Comment by ilmaren** [comment]
Hi,
Could you please report the problem and which solution you adopted?  (It could be useful for someone else).
Cheers

Inviato da Android.

-----Original Message-----
