### ISSUE TITLE
How to implement fixed height and disable scrolling?

### ISSUE THREAD

**Issue by GreeneDragon** [TwoBeers/shiword#34]
hi,

I love your theme. Thank you so much for sharing your wonderful creation with the world!

I have one page in which I'd like to use a fixed height for the content (I don't want the frame to stretch along with the window) and I do not want the page to be scrollable by the mouse wheel.

How should I implement this? Your help would be greatly appreciated!

Sincerely,

Jason

**Comment by jimo** [comment]
Hi Jason,
I'm not sure to have understood what your goal is...
Maybe a live check to your site, with an example page may help

Jimo

**Comment by GreeneDragon** [comment]
hello, Jimo:

Thanks for getting back to me so fast!

My site is not live just yet. I am only developing it on my own computer.
I'll try to explain my situation better.

I wanted to mimic an iPad by displaying a single image in the frame of
Shiwood (I am only doing this on one page, so WordPress and Shiwood logos
will still be there on all my other pages).

I successfully replaced the headerimg with my own and suppressed all other
content in the content area. Then I realized that I have two problems:
1. Shiwood stretches the frame according to the browser window size. This
   is like magic to me. It is wonderful everywhere else, but for this page I
   would like the frame to be exactly the size I want so that my picture is
   perfectly framed in it.
2. I would like to disable page scrolling on this page so that my picture
   won't move inside the frame.

Your help in achieving this would be greatly appreciated!

Jason

**Comment by jimo** [comment]
Ok now it's more clear.

I made a template for you: https://gist.github.com/jimo/5961569

Download this PHP file (shiword_splash_screen.php), move it to the Shiword folder, create a new page, insert an image, select the "Splash Screen" template and save.

Obviously you can edit this file as you like

Hope it fits your needs

**Comment by GreeneDragon** [comment]
Thank you so much for the amount of work you did for me. I installed the
template and the process was very smooth. And I saw that in the template
you have sections beginning with  "avoid frame resize" and "avoid
scrolling", which I suppose were added just for me!

so I made a page with the splash screen template, and the scrolling
function is indeed deactivated! However, the frame is still resizing along
with the window :(

It's probably something very small for you to fix, but for me, it's like
learning another language. Can you please take a look when you get a
chance?

I really appreciate your help!

**Comment by GreeneDragon** [comment]
I just realized that the splash screen template has a fixed width! I didn't
even realize the width changed too. I was only concerned with the height.
Can you add a fixed height? Also, how can I specify the width or height?

if ( $key == 'shiword_frame_width' ) $value = 850; // I tried changing this
number, but it doesn't seem to affect the width

**Comment by jimo** [comment]
Nop, changing it doesn't affect the width. The 'shiword_frame_width' can have 3 values: 626, 850 or 1106. They are respectively referring to the 'narrow','normal' and 'wide' frame size in theme options.
But in your splashscreen template the width is the 'normal' one anyway.

About the fixed-height, sorry but it's almost impossible (not bore you with the details). All you can do is using an image tall enough to fit big screens, being conscious it'll be cutted out in smallest ones

EDIT: I modified the template, so now you can use the width you prefer. Just search for the function 'shiword_custom_frame_width()' and, as noted inside it, change every 'width' rule by the same amount of pixels, eg 972px + 10px -> 982px, 850px + 10px -> 860px etc

**Comment by GreeneDragon** [comment]
I see. Thank you for the explanation! Nonetheless, I love the theme, and it
will be what I use for my website.

Thank you for all you have done for me! It is a pleasure to see generosity
from the free software community once again!

**Comment by jimo** [comment]
My pleasure! :)
