### ISSUE TITLE
It's for Buddypress? How can I change backgrond?

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#35]
Hi, I'm italian and dont't speak english very well.
Your theme shiword is wonderfull. I would like know how I can give you a very little donation of some euro (I don't work). However, I seen there are six background ((that with pink flowers, a city, double colour etc etc) and I can't put an image mine. It's is possible? 

Thank you very much
Francesco

**Comment by ilmaren** [comment]
Ciao Francesco,
scrivi tranquillamente in italiano (siamo italiani anche noi).

Per quanto riguarda buddypress, shiword nasce per WP e personalmente non l'ho testato con BP (forse Jimo si e nel caso ti risponderà lui appena rientra); ti consiglio di fare un test in locale, e valutare il funzionamento con il tema, prima di metterlo online.

Il discorso background in shiword è estremamente complicato (per quello sono attualmente così limitati, non escludo che ne vengano aggiunti in futuro), in quanto coinvolge sia le immagini che il css che il codice che genera il tema.

La via più facile (forse), che posso suggerirti è quella di creare un tema child (vedi http://twbrs.net/20), copiando la cartella (e il suo contenuto), dei background di shiword _images\backgrounds_, sostiutire una delle img presenti con la tua img di background e vedere cosa viene fuori.
P.S. l'immagine che utilizzerai dovrà avere le stesse dimensioni di quella che va a sostituire

Spero di esserti stato di aiuto.
Viva!

**Comment by franccicccio** [comment]
Ciao grazie per la risposta!

Ho testato BP in reazione con Shiword, e ho visto questi 2 difetti: 
- Quando si installa buddypress, compare la barra in alto. Ecco la barra
  copre il primo centimetro della pagina: non è carino a  vedersi e non è una
  grave cosa, ma se nelle prossime versioni tutto il disegno si spostaste 1 cm
  sotto, allora qualora si dovesse installare Buddypress non ci sarebbero
  sovrapposizioni barra/titolo del sito.
- Nella pagina "Gruppi", ci sono i gruppi ma manca il tasto "creazione
  Gruppi" che offre Buddypress. Questo è un difetto più grave.

Tutto qua. Per il resto, avrei 3 cose da notare per futuri sempre possibili
miglioramenti (li farei da solo se conoscessi il php o l'occorrente - quando
avrò tempo cercherò di imparare qualcosa per modificare da solo i temi WP9.
1. Ho notato che la funzione "cerca" da mettere in widget, è strana, cioè
   scrivo quel che devo cercare, batto su invio e cerco. Però manca un minimo
   di animazione che possa "certificare" che non ho battuto a vuoto. Il tasto
   funziona perfettamente, ma non si comporta come un tasto "dinamico".
   1. Ho installato il plugin Facebook Comments cosicchè il solito spazio
      commenti è coperto dal noto plugin facebook. Questo mi libera in un colpo
      solo da ogni forma di spam. Ho notato però che il pannello "Commenti recenti
      rimane sempre VUOTO ANCHE SE COMMENTO. Mi sono arrivate delle email di
      notifica commenti (fatti da me stesso) IN EMAIL, ma tali commenti non sono
      registrati nel pannello-widget di Shiword. 
2. Cosa devo fare per togliere l'autore dal pannello-widget "Articoli
   recenti" e "Categorie"? Che tu sappia, è possibile? Ho tolto il resto (data)
   ma l'autore (io) rimane. Vorrei comparissero come anonimi (tanto nel sito li
   scrivo tutti io).

Grazie mille per tutto

PS non ho ancora provato a cambiare il background e a fare il tema figlio
cmq ho messo del marmo nel contorno-dekstop e questo sta molto meglio con le
foglie di bambù preimpostate 

-------Messaggio originale-------

Da: ilmaren

Data: 23/07/2013 20:42:17

A: TwoBeers/shiword

Cc: franccicccio

Oggetto: Re: [shiword] It's for Buddypress? How can I change backgrond?
(#35)

Ciao Francesco,

scrivi tranquillamente in italiano (siamo italiani anche noi).

Per quanto riguarda buddypress, shiword nasce per WP e personalmente non l
ho testato con BP (forse Jimo si e nel caso ti risponderà lui appena
rientra); ti consiglio di fare un test in locale, e valutare il
funzionamento con il tema, prima di metterlo online.

Il discorso background in shiword è estremamente complicato (per quello sono
attualmente così limitati, non escludo che ne vengano aggiunti in futuro),
in quanto coinvolge sia le immagini che il css che il codice che genera il
tema.

La via più facile (forse), che posso suggerirti è quella di creare un tema
child (vedi http://twbrs.net/20), copiando la cartella (e il suo contenuto),
dei background di shiword images\backgrounds, sostiutire una delle img
presenti con la tua img di background e vedere cosa viene fuori.

P.S. l'immagine che utilizzerai dovrà avere le stesse dimensioni di quella
che va a sostituire

Spero di esserti stato di aiuto.

Viva!

—

Reply to this email directly or view it on GitHub.

 --

 Caselle da 1GB, trasmetti allegati fino a 3GB e in piu' IMAP, POP3 e SMTP autenticato? GRATIS solo con Email.it http://www.email.it/f

 Sponsor:

 Last Minute Luglio: Euro 70,00 tutto compreso + offerte per famiglie all'Hotel Baia Marina di Cattolica. Per info 0541958080

 Clicca qui: http://adv.email.it/cgi-bin/foclick.cgi?mid=12993&d=27-7

**Comment by jimo** [comment]
Ciao Francesco,

per il momento, come ha detto ilmaren e come hai potuto notare anche tu, Shiword non è del tutto compatibile con BuddyPress.
Stiamo aggiornando i nostri temi per renderli compatibili sia con BP che con bbPress, ma ci vorrà del tempo (e in questo periodo ne ho/abbiamo poco ;) )
Per il momento prova queste modifiche veloci:
- aggiungi il seguente codice CSS a style.css

```

.buddypress #head_cont {
    margin-top: 28px;
}

.buddypress .meta_container {
    display: none;
}

```
- nel file functions.php elimina la riga 57

```

add_filter( 'the_title'                             , 'shiword_title_tags_filter', 10, 2 );

```

Per il discorso background, confermo quello che ha detto e suggerito ilmaren

Riguardo alle note varie

1 - potrebbe essere una bella idea rendere il campo di ricerca più 'reattivo', grazie del suggerimento

2 - Non ho provato il plugin Facebook Comments, ma suppogo che i commenti scritti usando quel plugin non vengano memorizzati nel database di WP, quindi il tema (e wordpress stesso) non li riconosce (ma il plugin ovviammente si). Quindi non mi stupisco che i commenti non compaiano nel pannello 'Commenti Recenti'.
A questo punto ti consiglierei di disattivare il pannello stesso nelle opzioni del tema

3 - nel file quickbar.php sostituisci `'by %s'` con `''` (stringa vuota). Lo trovi due volte (righe 429 e 470)

**Comment by franccicccio** [comment]
Ciao ho provato l'ultimo consiglio e ha funzionato, per quanto riguarda la
barra  

superiore del tablet troppo superiore, aspetto futuri aggiornamenti in
quanto non so dove mettere mani.
1. Chiedo aiuto ora invece per la questione delle 2 barre laterali o "menù a
   scorrimento" di questo tema, in pratica mi pare di aver capito che NON SONO
   MODIFICABILI. Mi piacerebbe però aggiungervi delle icone mie personali in
   quanto ho notato che il tablet virtuale ha molto spazio poco sfruttato lungo
   i bordi. Sto parlando delle strisce dove voi avete messo le icone "home" 
   utente" "stampa" "articoli recenti" "commenti recenti" etc.

Considerato che ho una conoscenza html, css nulla (purtroppo non ho trovato
il tempo per studiare), potrei obbedendo fedelmente ai vostri precetti,
aggiungere io personalmente delle icone? Queste icone dovrebbero rimandare a
pagine/articoli/categorie ancora non ho l'idea precisa in mente. 
1. Anzi, mentre che ci sono, vorrei sapere se è possibile mediante queste
   icone, aprire delle pagine con un template personale, in una nuova finestra
   e quindi fuori dallo spazio nero di default del tema shiword, in cui le
   pagine si aprono INTERNAMENTE al piccolo schermo. Se avessi già creato una
   pagina internet e sapessi appiccicarla a un link, potrei appiccare il link a
   delle icone lungo i bordi del piccolo tablet senza che il tema impazzisca?
2. Anzichè "commenti recenti" nel menuù laterale a scorrimento , mi
   piacerebbe cambiare la dicitura in "Ultimi Contributi". Lo stesso per 
   Articoli Recenti".Come posso fare?

Grazie

Francesco

-------Messaggio originale-------

Da: jimo

Data: 30/07/2013 06:07:51

A: TwoBeers/shiword

Cc: franccicccio

Oggetto: Re: [shiword] It's for Buddypress? How can I change backgrond?
(#35)

Ciao Francesco,

per il momento, come ha detto ilmaren e come hai potuto notare anche tu,
Shiword non è del tutto compatibile con BuddyPress.

Stiamo aggiornando i nostri temi per renderli compatibili sia con BP che con
bbPress, ma ci vorrà del tempo (e in questo periodo ne ho/abbiamo poco ;) )

Per il momento prova queste modifiche veloci:

aggiungi il seguente codice CSS a style.css .buddypress #head_cont {
margin-top: 28px; } 

nel file functions.php elimina la riga 57 add_filter( 'the_title' , 
shiword_title_tags_filter', 10, 2 ); 

Per il discorso background, confermo quello che ha detto e suggerito ilmaren

Riguardo alle note varie

1 - potrebbe essere una bella idea rendere il campo di ricerca più 'reattivo
, grazie del suggerimento

2 - Non ho provato il plugin Facebook Comments, ma suppogo che i commenti
scritti usando quel plugin non vengano memorizzati nel database di WP,
quindi il tema (e wordpress stesso) non li riconosce (ma il plugin
ovviammente si). Quindi non mi stupisco che i commenti non compaiano nel
pannello 'Commenti Recenti'.

A questo punto ti consiglierei di disattivare il pannello stesso nelle
opzioni del tema

3 - nel file quickbar.php sostituisci 'by %s' con '' (stringa vuota). Lo
trovi due volte (righe 429 e 470)

—

Reply to this email directly or view it on GitHub.

 --

 Caselle da 1GB, trasmetti allegati fino a 3GB e in piu' IMAP, POP3 e SMTP autenticato? GRATIS solo con Email.it http://www.email.it/f

 Sponsor:

 Offerta genitori single all'Hotel Antibes di Riccione: 1 Adulto + 1 Bambino = 920 euro; 1 Adulto + 2 bambini= 1110 euro. Pensione completa bevande incluse, Servizio spiaggia e ingresso ai parchi

 Clicca qui: http://adv.email.it/cgi-bin/foclick.cgi?mid=13029&d=13-8

**Comment by ilmaren** [comment]
Ciao Francesco,
scusa per i tempi lunghi, ma eravamo in ferie.

1 e 2) Realizzare quello che chiedi comporta numerose modifiche al tema originale e aggiungere diverse pagine template appositamente realizzate. Il tutto richiede anche una discreta, se non avanzata, conoscenza di HTML, CSS e PHP, quindi guidarti vorrebbe dire fornirti il lavoro completo. Mi spiace (non prendertela), ma questo non ci è possibile per mancanza di tempo (ci dedichiamo ai temi di WP solo per passione e nel poco tempo libero), e di voglia (il tema lo abbiamo fatto così perchè ci piace così, cambiarlo non ha senso per noi).

3) dare lo stesso nome a due finestre potrebbe essere fuorviante, comunque puoi modificare la traduzione modificando il file it_IT.po contenuto nella cartella "languages". Per aprirlo utilizza poedit e modifica le voci "Recent Comments" e "Recent Posts". una volta fatto salva normalmente e fai anche "salva con nome" e salva come it_IT.mo

Terremo conto delle tue richieste come suggerimenti per le future release.
Ciao e buon blogging

**Comment by franccicccio** [comment]
Ciao! Capisco che, in effetti, se una cosa si concepisce in un modo, in quel
modo dovrebbe restare. Capisco anche la mancanza di tempo :/

Per quanto riguarda il punto 3, credo di aver spiegato male per iscritto il
mio pensiero; ho scritto:
1. Anzichè "commenti recenti" nel menù laterale a scorrimento , mi
   piacerebbe cambiare la dicitura in "Ultimi Contributi". Lo stesso per 
   Articoli Recenti".Come posso fare?

Ecco non volevo dire che desidero mettere lo stesso nome "Ultimi Contributi"
sia alla paginetta "Articoli Recenti" che alla paginetta "Commenti Recenti".

Volevo chiedere come cambiare tutti e due i titoli con altri, che saranno: 
Ultimi Contributi alla PWiki" per la sezione commenti, e "Ultimi Articoli
Inseriti nella PWiki" per la sezione articoli. 

Ho avuto già modo di scartabellare con poedit e i file di traduzione, ma
volevo evitare di utilizzare questa scorciatoia in quanto sembra trattarsi
di modifiche molto semplici al "core" centrale, già in italiano! Perciò
potresti dirmi quali file e righe dovrei sovrascrivere esattamente? 
Grazieeee  scusami sono ignorante, dovrei una volta o l'altra farmi un bel
corso.

Ah! Solo ora mi vengono in mente due altre questioni:
1. Ho notato che l'immagine di testata pure quelle in dotazione, tiene un
   filo "incoerente" proprio sopra l'immagine, sotto il bordo superiore del
   cruscotto. Ho messo l'immagine di esemplificazione in allegato. 

Per l'immagine che ho scelto, quella con i palazzi grigi e le strade in
città, non è tanto grave. Non ho capito se la difformità è intenzionale, io
cmq posso tenermela questa linea, non si nota poi tanto in mezzo ai grigi e
ai neri anzi sembra fatta apposta. Ma ho provato ad esempio a metterci la
testata da voi fornita quella con le farfalle arancioni in gif, e allora il
filo di sopra in effetti stona!
1. Non vorrei esagerare con le richieste. Chiedo solo per chiedere: mi
   piacerebbe associare una frase proprio sopra o sotto il box dei commenti.
   sarà visibile ogniddove comparirà il box dei commenti. E' possibile? E'
   possibile PER ME metterla in quattroequattrotto?

Vorrei anche cambiare la frasetta "Lascia un commento" con "Lascia un
Contributo"

Il box dei commenti su wordpress è per me cmq qualcosa da cambiare: a parte
gli angoli troppo acuti (li arrotonderei un pò) sotto ci sono degli avvisi
sul linguaggio html brutt a vedersi e che (quasi) nessuno capisce. Mi chiedo
come mai in alcuni siti wordpress questa lista c'è, mentre in altri scompare
e il tutto sembra più pulito. C'è un modo semplice perchè anch'io possa
togliere l'incomprensibile frase:  

È possibile utilizzare questi tag ed attributi XHTML: <a href="" title="">
<abbr title=""> <acronym title=""> <b> <blockquote cite=""> <cite> <code>
<del datetime=""> <em> <i> <q cite=""> <strike> <strong>

-------Messaggio originale-------

Da: ilmaren

Data: 27/08/2013 22:01:10

A: TwoBeers/shiword

Cc: franccicccio

Oggetto: Re: [shiword] It's for Buddypress? How can I change backgrond?
(#35)

Ciao Francesco,

scusa per i tempi lunghi, ma eravamo in ferie.

1 e 2. Realizzare quello che chiedi comporta numerose modifiche al tema
originale e aggiungere diverse pagine template appositamente realizzate. Il
tutto richiede anche una discreta, se non avanzata, conoscenza di HTML, CSS
e PHP, quindi guidarti vorrebbe dire fornirti il lavoro completo. Mi spiace
(non prendertela), ma questo non ci è possibile per mancanza di tempo (ci
dedichiamo ai temi di WP solo per passione e nel poco tempo libero), e di
voglia (il tema lo abbiamo fatto così perchè ci piace così, cambiarlo non ha
senso per noi).

dare lo stesso nome a due finestre potrebbe essere fuorviante, comunque puoi
modificare la traduzione modificando il file it_IT.po contenuto nella
cartella "languages". Per aprirlo utilizza poedit e modifica le voci "Recent
Comments" e "Recent Posts". una volta fatto salva normalmente e fai anche 
salva con nome" e salva come it_IT.mo 

Terremo conto delle tue richieste come suggerimenti per le future release.

Ciao e buon blogging

—

Reply to this email directly or view it on GitHub.

 --

 Caselle da 1GB, trasmetti allegati fino a 3GB e in piu' IMAP, POP3 e SMTP autenticato? GRATIS solo con Email.it http://www.email.it/f

 Sponsor:

 BARBAPAPA': Acquista i Peluche Originali su mistercupido.com

 Clicca qui: http://adv.email.it/cgi-bin/foclick.cgi?mid=12898&d=27-8

**Comment by ilmaren** [comment]
Ciao di nuovo :-)

3) La core è in inglese e tutti i testi in italiano vengono generati tramite i file di traduzione, per questo ti consiglio di modificare quei file inserendo le frasi da te scelte al posto delle traduzioni italiane originali (conservando i file della traduzione da un'altra parte questo ti consentirà di non perdere tutto il lavoro fatto con i futuri aggiornamenti).

4) Non riesco a capire di che filo parli: l'allegato non è visibile inviandolo via mail, dovresti entrare in github e allegarlo nel commento

5) Il "lascia un commento" si può variare sempre tramite file di lingua
Il comment form viene generato e gestito direttamente da WP, dovresti vedere di qualche plugin che ti permetta di modificarne aspetto e comportamento
Nel frattempo puoi inserire del css personalizzato nelle opzioni del tema (pagina "altro"), per far sparire le scritte e addolcire i bordi:

``` css
.form-allowed-tags { display: none; }
#comment { border-radius: 5px; }
```

**Comment by jimo** [comment]
visto che questa issue è stata suddivisa in 3-4 altre issues, direi che la si può tranquillamente chiudere
