### ISSUE TITLE
RSS feed at the top right of my site

### ISSUE THREAD

**Issue by ReySMello** [TwoBeers/shiword#36]
Is there a way to remove the RSS link at the top of my web site? I've unchecked the option in the theme option but it is still showing up on my page. http://PlayboyEnergyDrink4You.com... Thanks for your help and support, Rey (ReyS@Mellomida.com)

**Comment by jimo** [comment]
Two ways:

1 - add the following css code to the Custom CSS field in theme options

```
#rss_imglink {
    display:none;
}
```

2 - or open functions.php and delete (line 1122->1128)

```
?>
    <div id="rss_imglink" class="minibutton">
        <a href="<?php echo esc_url( apply_filters( 'shiword_filter_rss_service', get_bloginfo( 'rss2_url' ) ) ); ?>" title="<?php esc_attr_e( 'Syndicate this site using RSS 2.0', 'shiword' ); ?>">
            <span class="minib_img">&nbsp;</span>
        </a>
    </div>
<?php

```

**Comment by ilmaren** [comment]
User solved the issue, but no feedback.
Issue closed
