### ISSUE TITLE
Filo incoerente

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#37]
Ho notato che l'immagine di testata pure quelle in dotazione, tiene un filo "incoerente" proprio sopra l'immagine, sotto il bordo superiore del cruscotto. Ho messo l'immagine di esemplificazione in allegato. 
Per l'immagine che ho scelto, quella con i palazzi grigi e le strade in città, non è tanto grave. Non ho capito se la difformità è intenzionale, io cmq posso tenermela questa linea, non si nota poi tanto in mezzo ai grigi e ai neri anzi sembra fatta apposta. Ma ho provato ad esempio a metterci la testata da voi fornita quella con le farfalle arancioni in gif, e allora il filo di sopra in effetti stona!

![filo incoerente](https://f.cloud.github.com/assets/4928663/1137782/80a194c8-1c66-11e3-82a4-1aa121597920.PNG)

Beh ho proprio adesso ricaricato l'immagine, sia quella che uso sia quella con le farfalle arancioni, e non vedo più alcun filino difforme! Non so se è un caso cmq per quella in gif tale "correzione" ci voleva proprio, per quella coi palazzi n effetti ora potendo fare il confronto... il filino ci stava bene! vabbè sono incontentabile cmq ora ci metto quella animata in arancio che è di grande effetto

**Comment by jimo** [comment]
E' un discorso di posizionamento/padding/margini etc etc. Non è facile in certe situazioni fare tutto precisissimo ;)
Comunque con la nuova versione (che è già presente qui su github) il problema dovrebbe essere risolto
