### ISSUE TITLE
Personalizzare un pò il box commenti

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#38]
Salve, 1 mesetto fa circa ho chiesto informazioni su come togliere il solito drim dram di informazioni html sotto il box commenti. Mi è stato risposto di aggiungere una particolare stringa di codice nella sezione "altro" in "opzioni tema", nell'opportuna sezione in bianco, e la magia ha funzionato! Incredibile! 
Ho chiesto anche come arrotondare i bordi, e con una nuova formuletta anche i bordi ho potuto arrotondare. Siccome il risultato mi piace, non ho motivo di installare plugin.

Però
1. Invece dei suggerimenti html, posso aggiungere una frase mia di seneca? Il principio è questo: come da qualche parte nelle cartelle del programma erano certamente scritti i suggerimenti html, così in teoria potrei cambiarli scrivendo altre cose, se solo sapessi dove devo andare a pescare la frase!
2. Mi piacerebbe moltissimo aggiungere anche una piccolissima immagine/icona alla fine della frase di seneca, con un link a un certo articolo che ho scritto. Quindi dovrei non solo personalizzare la frase, ma anche "caricarla" di contenuti (immagine con link). Potrei farlo?

Grazie mille
Francesco

**Comment by jimo** [comment]
Ciao,
ci sono un mare di guide e tutorial in giro per personalizzare il comment form... basterebbe cercare con Google... ;)

Per velocizzare la cosa, ecco cosa si può fare:

Apri functions.php e trova la funzione `shiword_comment_form_defaults` (riga 1938 circa) e aggiungi

```
$defaults['comment_notes_after']    = 'metti qui il tuo testo';
```

PRIMA della riga `return $defaults;`

Qui trovi una bella guida sul comment form: http://ottopress.com/2010/wordpress-3-0-theme-tip-the-comment-form/

Comunque, seriamente, dovresti cercare di personalizzare il tuo sito da te o altrimenti trovare qualcuno che lo faccia per te. Noi possiamo dare qualche suggerimento sulla personalizzazione del tema ma non fare siti su misura

**Comment by franccicccio** [comment]
Capisco che ognuno ha il proprio tempo per fare il proprio lavoro e non il lavoro degli altri, ma a volte l'ignoranza è tale che non si neppure cosa cercare! Ad esempio io non sapevo che questo lavoro potesse farlo CHIUNQUE; trattandosi del box commenti DI UN TEMA PRECISO, pensavo che solo "il capo" sapesse ove mettere le mani in quel tema preciso. Ma evidentemente non è così e il comment form in wordpress è INDIPENDENTE DAL TEMA, ciò per cui esistono dei tutorial PUBBLICI. Non so se mi sono spiegato bene. Cmq già queste indicazioni che hai dato sono preziose e ti ringrazio, vado a leggere! (e a fare)
