### ISSUE TITLE
Compatibilità con Buddypress

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#40]
Salve tempo fa avevo notato che installando buddypress non si aveva a disposizione semplicemente il tasto "crea gruppo"; poi c'ra il problema della barra troppo bassa e basta. La scorsa settimana ho invece scoperto un superproblema: quando cancello un gruppo, si cancella automaticamente la pagina dei gruppi con relativa voce nel menù. Scompare tutto. 
Quando invece cancello un utente, si cancella dal tema tutta la pagina dei membri, con relativo link dal menù. Certo questo rende il tema da parte mia inutilizzabile ma è troppo bello e non ci rinuncio: aspetterò con pazienza benevoli aggiornamenti tanto il sito giungerà a maturità fra qualche anno...

Francesco

**Comment by jimo** [comment]
Se ti scarichi lo zip della versione che è attualmente qui su github, la maggior parte dei problemi grafici dovrebbe essere risolta. X quel che riguarda le misteriose sparizioni delle pagine... boh. Se ho tempo proverò a vedere. Comunque sono quasi convinto che sia questione di plugin. Magari fai la prova con un altro tema

**Comment by franccicccio** [comment]
Ciao a tutti, annuncio pubblicamente un fenomeno di "guarigione spontanea"!
Con la nuova versione di buddypress rilasciata qualche mese fa, adesso il tasto "crea gruppo" è tornato disponibile, ANCHE SU SHIWORD! Quindi non occorre rivedere questa parte ;)

**Comment by franccicccio** [comment]
è nella sezione gruppi!

**Comment by franccicccio** [comment]
funziona! Ma è il css è tutto da sistemare ed alcune funzioni da ristrutturare :/ vabbè la base cmq è fatta :) 
Ascolta ti ho risposto anche sul Caroseul del Thickbox nell'altro post ma essendo chiuso non vorrei che ti sfuggisse!
