### ISSUE TITLE
Tasto donazioni

### ISSUE THREAD

**Issue by franciccio** [TwoBeers/shiword#41]
Ciao non sapevo dove mettere quest'annuncio. Siccome l'altro giorno ho avuto una piccola fortunata rendita, ho pensato di spartirla col mondo OS che mi ha dato tanto con questo wordpress senza chiedermi nulla. Se mettete un tasto donazioni, farò una donazione, PERO' non quella normale! Paypal permettte di creare dei tasti per PAGAMENTI AUTOMATICI MENSILI. Così, la mia donazione di 25 euro verrà dilazionata in 1 euro al mese in 2 anni, corrispondente a 12 euro all'anno, prorogabile per gli anni a venire se avrò altre piccole rendite. Faccio già la stessa cosa con un altro plugin scaricato per WP, ed infatti da quel tale ho preso quest'idea, che ho messo pure nel mio sito al posto del solito tasto donazione una tantum. Paypal fa tutto da solo, non mi chiede consensi ed invia a giorni fissi, mi pare il meccanismo dello stipendio! Naturalmente, non lavorando, più di 1 euro anzi a volte anche meno - il soldi per un lecca lecca - non cedo anche perchè vanno cumulandosi con altre forma di offerta libera.

**Comment by ilmaren** [comment]
Ciao,
attualmente non accettiamo donazioni.
Grazie e buon lavoro
