### ISSUE TITLE
Togliere il riassunto degli articoli quando si ricerca per categoria

### ISSUE THREAD

**Issue by franciccio** [TwoBeers/shiword#42]
Ciao ecco ho appunto questa esigenza, e sono andato su internet per scoprire come si fa. Ho scoperto che devo toccare il file Editor e poi quello chiamato 'template categorie' (category.php); si diceva che la parte di codice responsabile di far apparire il riassunto è questa:

<?php the_excerpt(); ?>

ma poi mancavano indicazioni pratiche su come procedere. Ve ne sarei grato se mi aiutaste. In pratica quando cerco qualcosa dalla barra di ricerca e compare la lista degli articoli, questi portano immediatamente sotto qualche riga di introduzione... beh a me pare porti più confusione che altro, perciò vorrei toglierla completamente...

**Comment by ilmaren** [comment]
Ciao,
apri loop\post.php con un editor di testo e sostituisci (linee 29 e 30)

```
                the_excerpt();
            else
```

con

```
            /** no excerpt
                the_excerpt();
            else
            end **/
```

**Comment by ilmaren** [comment]
ricorda che ai successivi update la modifica verrà persa e sarà necessario rifarla

**Comment by franciccio** [comment]
ciao grazie per l'info; ma ti riferisci agli udate del tema shiword, o agli udate di wordpress?

**Comment by franciccio** [comment]
allora, ho fatto tale e quale come hai detto, ma il risultato è che gli articoli di una categoria si aprono tutti interamente in lista, mentre io volevo che la lista degli articoli fosse solo dei TITOLI, senza alcun contenuto. Ora il contenuto si offre immediatamente e COMPLETAMENTE quando clicco sul pulsante che linka a una categoria.
Non so se il problema sia dovuto a questione di spazi vuoti. Infatti il tuo codice come l'hai riportato sopra è messo ben in fila, mentre quando l'ho incollato nell'apposito spazio (riga 28 e 29), le 4 strighe si sono sparse un pò a casaccio, disomogeneamente su 4 righe. Poi tutto il resto è rimasto uguale. Il cambiamento c'è stato evidente, ma non nella forma voluta :/

**Comment by ilmaren** [comment]
quindi vuoi lasciare solo il titolo.
ok, stesso file, stesse righe, elimina completamente

```
                the_excerpt();
            else
                the_content();
```

o meglio, se sono quelle modificate come sopra

```
            /** no excerpt
                the_excerpt();
            else
            end **/
                the_content();
```

**Comment by franciccio** [comment]
ok perfetto, in effetti rileggendo sono stato impreciso nella richiesta iniziale. Grazie un'altra volta! :)

**Comment by ilmaren** [comment]
ok,
closed
