### ISSUE TITLE
Condivisione su g+

### ISSUE THREAD

**Issue by franciccio** [TwoBeers/shiword#43]
Salve, ho notato che il widget condivisione articolo tiene molte opzioni di condivisione su molti social network: facebook , twitter ed un'altra decina, ma non considera google+. Non so se è una scelta o una svista cmq io la dico... ciao!

**Comment by jimo** [comment]
Ciao, grazie per l'info, probabilmente è una svista. Difficilmente però verrà aggiunto in futuro.
Anticipo infatti che (probabilmente) nelle future versioni, alcuni widget spariranno definitivamente, compreso quello di condivisione

**Comment by franciccio** [comment]
ma no no no e poi no :) è extra-utile quel widget incorporato nel tema stesso! Ma lo sostituirete con un altro o proprio nisba?

**Comment by jimo** [comment]
Verrà proprio eliminato, visto che ci sono plugin che fanno la stessa cosa.

**Comment by ilmaren** [comment]
E aggiungiamo pure che su WP, ci fanno ogni volta mille storie se inseriamo nei temi delle funzioni che vengono considerate di pertinenza dei plugin (come, appunto, la condivisione con i vari social).

**Comment by franciccio** [comment]
beh però il vostro "plugin" è incorporato al tema e non dovrebbe mai entrare in conflitto o "invecchiare", mentre un plugin estraneo potrebbe dare conflitti e se non aggiornato via via che la piattaforma wordpress si evolve (3.9, .4.0 etc etc), potrebbe pure andare in crash. Cmq vabò pazienza

**Comment by ilmaren** [comment]
Pienamente d'accordo, grazie all'ottimo lavorod di Jimo i nostri temi sono sempre aggiornati e compatibili.
Tuttavia, come ho scritto sopra, è proprio volontà di WP che i temi non contengano nient'altro se non elementi strettamente collegati alla grafica, e l'inserimento di questi "plugin" ci costa, ogni volta, numerose battaglie e notevoli ritardi nel rilascio ufficiale del tema aggiornato.
