### ISSUE TITLE
Posizione dei blocchi di testo nell'Area Widget degli Articoli

### ISSUE THREAD

**Issue by franciccio** [TwoBeers/shiword#44]
Scusate, mi piacerebbe sapere se ho un modo per METTERE AL CENTRO il blocco in basso che mi compare a sinistra
![fondo](https://f.cloud.github.com/assets/4338836/2051154/456e3f32-8a84-11e3-8543-53694cb288a2.PNG)
Da qualche mese spezzo e compongo tasselli per cercare di rendere ordinata questa sezione, ma non ci riesco. ll widget articoli ha attualmente 3 blocchetti: la stella, il widget-condividi e un blocco di testo vario. Purtroppo se cambio l'ordine e allineamenti ottengo:
![fondo2](https://f.cloud.github.com/assets/4338836/2051175/9b9fc952-8a84-11e3-821a-4ccfcd7c493c.PNG)
In pratica il blocco di sotto sta o tutto a destra, o tutto a sinistra, e mai al centro. C'è qualcosa che potrei facilmente fare per sistemarlo? Capisco che la soluzione può essere complicata ma almeno chiedo...

**Comment by jimo** [comment]
Non è complicato, basta sapere come fare. Ti faccio un esempio usando Firefox
- installa Firefox e l'addon Firebug
- clicca col tasto dx sopra l'elemento che vuoi modificare, in questo caso il widget, e seleziona "controlla elemento con firebug"
- nella finestrella che compare, individua il blocco (div) del tuo widget.
- copia l'id, che in questo caso è "black-studio-tinymce-6" e chiudi pure la finestra di firebug
- adesso vai alla pagina delle opzioni del tema e, nel campo "custom CSS" aggiungi una cosa del genere

```
#black-studio-tinymce-6 {width: 100%;}
```

e salva le opzioni

Ora il widget dovrebbe posizionarsi al centro occupando l'intera larghezza.
Avrei potuto dirti semplicemente di incollare la modifica css alle opzioni, ma l'ho voluta prendere alla larga per spiegare qual'è il procedimento

**Comment by franciccio** [comment]
l'id/ stringa del blocco che compare grazie a firebug è corretta mi chiedo come mai tu la conoscevi già, cmq non mi funziona! per piacere aspettate qualche giorno prima di chiudere questa issue, nel frattempo vedo meglio con firebug magari cambio id e provo a spostare altri settori

**Comment by jimo** [comment]
scusa, errore mio

```
#single-widget-area #black-studio-tinymce-6 {width: 100%;}
```

così dovrebbe funzionare
comunque, la conoscevo perchè l'ho vista nel tuo sito

**Comment by franciccio** [comment]
splendidooooooooo grazie si così è messa al centro ed è una incredibile soddisfazione vedere che funziona dopo essermici fritto il cervello. Ascolta le stringhe che suggerisci le conosci tutte a memoria oppure c'è un libro agile e veloce che bisogna consultare per rendersi indipendenti?

**Comment by jimo** [comment]
In pratica le conosco a memoria. Non saprei consigliarti un libro, visto che non ne ho mai usato uno (a parte uno di css avanzato).
Dando un'occhiata ad amazon, questo potrebbe essere interessante ed i commenti sono molto positivi: http://www.amazon.com/CSS3-Missing-David-Sawyer-McFarland/dp/1449325947/ref=pd_sim_b_1
Comunque ricordo che questo sito è piuttosto utile: http://w3schools.com/

**Comment by franccicccio** [comment]
ho applicato il procedimento con un'altra coppie di icone inspiegabilmente compresse ed ha funzionato wow
