### ISSUE TITLE
Forzare l'Avatar

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#45]
Allora questo è un discorso complicato per risolvere il quale so già che dovrò cercare e pagare uno sviluppatore buddypress, ma prima chiedo qui non si sa mai!
Allora, quando un utente si iscrive al sito, gli viene data la possibilità di scegliere un avatar. 
La possibilità di scegliere e cambiare l'avatar è messa anche nel pannello di controllo utente.
Ecco a me piacerebbe che i membri non scegliessero immagini proprie, ma scelgano solo e soltanto fra quelle consigliate da me in una lista di immagini che avrò precedentemente caricato in una cartella del sito.
Semplice a dirsi, ma complicato a farsi? 
Chiedo qui perchè ho notato che Shiword già "suggerisce" delle immagini standard (quelle dell'utente anonimo), quindi mi vien da pensare che la stessa cosa potrebbe facilmente fare con gli utenti non-anonimi. Tutti "costretti" entro un solo paniere di avatar.
Sinceramente, mettendomi a studiare un pò di php potrei fare facilmente io questa cosa, oppure è così sofisticata che è meglio ricorrere subito a un professionista?

Grazie per il consiglio

**Comment by jimo** [comment]
Non ho il codice di buddypress sotto mano, inoltre è parecchio complicato, quindi non saprei aiutarti. Comunque, prima di pagare qualcuno, ti suggerisco ti chiedere nel forum di supporto del plugin. Magari è più semplice del previsto

**Comment by franccicccio** [comment]
Eh no in quel forum ormai si possono intercettare pure le ragnatele. L'unico benefattore italiano (preparato) che stava lì, dacchè ha avuto un bambino, pare aver abbandonato noi comuni disperati. Cmq ti ringrazio ugualmente per il consiglio e se mi contatti in pvt, se vuoi, puoi anche darmi la tua tariffa per un simile compito, così tanto per farmi un'idea.

**Comment by franccicccio** [comment]
eventualmente puoi contattarmi su fb http://www.facebook.com/francesco.provenzano.313

**Comment by jimo** [comment]
Eccomi. Scusa ma in questo periodo ero un po' impegnato.
Il discorso è che non saprei nemmeno da dove iniziare, e soprattutto suppongo che ci sia da modificare pure il codice di wordpress stesso, oltre che a quello di buddypress, in quanto wp prima cerca se c'è un avatar associato ad un eventuale account gravatar, poi eventualmente si può caricarne uno a piacere. Veramente è un bel problema e non ho le conoscenze per farlo, non è un discorso di tariffe, mi spiace.

**Comment by jimo** [comment]
Tra l'altro, prova a vedere se esiste un plugin per farlo.
Dando un'occhiata veloce ho trovato questi:
http://wordpress.org/plugins/bp-avatar-suggestions/
http://wordpress.org/plugins/bp-blog-avatar/
Magari ti possono aiutare

**Comment by jimo** [comment]
A quanto pare http://wordpress.org/plugins/bp-avatar-suggestions/ è esattamente il plugin che fa per te! \o/

**Comment by franccicccio** [comment]
grazie gentilissimo lo proverò non appena posso al momento ho WP rotto un aggiornamento riuscito male e sono 15 giorni che commatto con l'assistenza aruba :) 
Non avevo pensato di ricorrere al plugin perchè pensavo fosse una potenzialità inclcusa o facilmente includibile dal vostro tema.
Ok puoi chiudere il topic ma se non ti dispiace potresti darmi un consiglio off-topic? Un importante plugin che utilizzavo per BP non è più supportato dal suo autore e adesso mi tocca recuperarlo facendo un serio corso di programmazione. L'alternativa è reinstallare la vecchia versione di WP in cui funzionava. Secondo te è saggio raggiungere una specie di "climax" (equlibrio dell'ecostistema informatico interno al sito) e poi ignorare qualsiasi aggiornamento di WP?
Così il mio sito si fermerebbe a WP 3.9 o anzi 3.7 mentre negli anni quello correrà e diventerà WP 4, 5, 6 etc etc. I plugin non tengono sempre il passo e dovrei essere un esperto per aggiornarli io al posto dei loro autori. Un sito con una versione di WP molto vecchia ne risentirebbe in termini di stabilità e sicurezza?

**Comment by jimo** [comment]
uhmm, il discorso è complicato perchè ci sono molti pro e contro. A parte la questione bugfix, nuove funzionalità etc, gli aggiornamenti di wp (e dei plugin) alle volte sistemano alcune falle alla sicurezza.
Io la vedo così: se uno non ha un sito particolarmente "esposto" (tipo il New York Times ;) ), con un numero molto limitato di accessi, potrebbe teoricamente permettersi di ignorare gli aggiornamenti (le falle solitamente si riferiscono a dei casi limite), statisticamente il rischio è basso.
Tieni conto comunque che, ad esempio, il nostro sito, benchè abbia un limitato numero di accessi ed una visibilità altrettanto limitata, viene attaccato quotidianamente da svariati amici cinesi, russi e/o iraniani :D
