### ISSUE TITLE
Controllare il numero di "commenti recenti" e di "articoli recenti" nelle 2 finestre in basso a sinistra del table

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#46]
Ho passato a rassegna le "opzioni tema" fornite dal tema, forse sarò orbo ma non ho trovato come scegliere la quantità da mostrare!
Eppure molto tempo fa la scelsi! 7 commenti recenti e solo gli ultimi 10 articoli tra i nuovi. Questi numeri li ho scelti io1-2 anni fa, ma non ricordo come ho fatto! Vorrei cambiarli ma ne in aspetto nè in personalizzazione ho trovato pannello...
Qualcuno potrebbe aiutarmi?

**Comment by ilmaren** [comment]
Questa è un'impostazione propria di WP, nn riguarda il tema. Cerca tra le impostazioni di WP.
Ciao
Inviato da BlackBerry®

-----Original Message-----

**Comment by jimo** [comment]
Ma intendi gli elenchi che stanno nei pannelli scorrevoli in basso? In questo caso non c'è (e per la verità non c'è mai stata ) l'opzione per modificare il numero

**Comment by jimo** [comment]
Se intendi proprio quelli, devi aprire quickbar.php e cercare le funzioni `shiword_get_recentcomments` e `shiword_get_recententries` e modificare il valore `number` delle ricerche

**Comment by ilmaren** [comment]
mi ero perso il "nelle 2 finestre ..."

**Comment by franccicccio** [comment]
...si mi riferisco ai due pannellini scorrevoli in basso a sinistra: "commenti recenti" e "articoli recenti". 
Allora, su WP non ho trovato il metodo per definire questa cosa. Credo che definii la quantità di 7 per i commenti recenti nel widget commenti di WP, ma quando avevo messo un altro tema. Poi l'ho cambiato con Shiword ma la vecchia impostazione è rimasta, in qualche modo. 
Sul file quickbar.php ho trovato la stringa degli articoli recenti shiword-get-recentries ed in effetti il numero cambia subito! Fatto! Invece per shiword-get-recentcomments non c'è una stringa del valore come nell'altro caso, e perciò non sono riuscito nell'impresa. Ho cambiato l'unico numero che ho trovato in mezzo ad altri codici ma non ha funzionato. Ad ogni modo grazie ugualmente

**Comment by franccicccio** [comment]
incollo qui tutta la funzione magari può aiutare. attualmente sono visibili solo 7 commenti e vorrei estendere questo numero a 11, ma non vedo 7 da nessuna parte:

```
// Get Recent Comments
if ( !function_exists( 'shiword_get_recentcomments' ) ) {
    function shiword_get_recentcomments( $echo = 1 ) {
        $comments = get_comments( 'status=approve&number=10&type=comment' ); // valid type values (not documented) : 'pingback','trackback','comment'
        $output = '';
        if ( $comments ) {
            foreach ( $comments as $comment ) {
                //if ( post_password_required( get_post( $comment->comment_post_ID ) ) ) { continue; } // uncomment to skip comments on protected posts. Hi Emma ;)
                $post = get_post( $comment->comment_post_ID );
                setup_postdata( $post );
                //shrink the post title if > 35 chars
                $post_title_short = mb_strimwidth( get_the_title( $post->ID ), 0, 35, '&hellip;' );
                if ( post_password_required( $post ) ) {
                    //hide comment author in protected posts
                    $com_auth = __( 'someone','shiword' );
                } else {
                    //shrink the comment author if > 20 chars
                    $com_auth = mb_strimwidth( $comment->comment_author, 0, 20, '&hellip;' );
                }
                $output .= '<li>'. $com_auth . ' ' . __( 'on', 'shiword' ) . ' <a href="' . esc_url( get_permalink( $post->ID ) . '#comment-' . $comment->comment_ID ) . '">' . $post_title_short . '</a><div class="preview">';
            if ( post_password_required( $post ) ) {
                $output .= '[' . __( 'No preview: this is a comment of a protected post', 'shiword' ) . ']';
            } else {
                $output .= get_comment_excerpt( $comment->comment_ID );
            }
                $output .= '</div></li>';
            }
        } else {
            $output .= '<li>' . __( 'No comments yet.', 'shiword' ) . '</li>';
        }
        if ( $echo )
            echo $output;
        else
            return $output;
    }
}
```

**Comment by jimo** [comment]
La riga che devi modificare è la 4 del codice che hai incollato

```
$comments = get_comments( 'status=approve&number=10&type=comment' ); // valid type values (not documented) : 'pingback','trackback','comment'
```

al posto di `number=10` devi mettere `number=11`
Che poi non so perchè attualmente ti visualizzi 7 commenti invece che 10. Ci sono più di 7 commenti sul tuo sito?

**Comment by jimo** [comment]
Comunque forse in futuro potremmo aggiungere un'opzione per scegliere quanti commenti/articoli visualizzare, così non ci sarà più bisogno di modificare il codice

**Comment by franccicccio** [comment]
ahahah hai ragione forse non ci sono più di 7 commenti nel mio sito! che è online solo in versione test e i commenti sono prove tutte mie! Hai ragione verificherò non appena tornerò ad avere un sito modificabile.

**Comment by franccicccio** [comment]
Buongiorno! Il mio sito è tornato agibile. Ecco ho verificato e avevo fatto male i conti con l'interpretazione del termine "commento". Siccome ho installato buddypress, pensavo che rispondere ai commenti era una risposta ai commenti, e invece no, meglio così! In effetti a me importa che la finestrella in basso a sinistra tenga conta dei commenti standard, non quelli fatti sulle pagine-buddypress. Vabbè non si è capito molto, cmq il risultato è che il codice che hai fornito funziona e questo thread si può chiudere!
Ma un'ultima cosa a proposito della finestrella shiword in basso a sinistra: è possibile mettere in essa un link per visualizzare commenti OLTRE il numero visualizzabile dalla finestrella, che attualmente è 12?

**Comment by jimo** [comment]
Ciao, bentornato. Sinceramente non mi viene in mente un modo per aggiungere questo link, anzi per visualizzare gli altri commenti (per aggiungere un link è questione di 30 secondi ;) ).
Forse creando una pagina ad hoc con un template personalizzato per visualizzare una lista di commenti... ma mi pare macchinoso.
Mi spiace, mi sa che sta volta non posso aiutarti
