### ISSUE TITLE
Spostare la slideshow su pagine diverse dalla homepage

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#47]
Ciao avrei l'esigenza di spostare la bella slideshow di Shiword, su una pagina che non sia la homepage. Ho cercato nelle opzioni ma ho trovato solo l'opzione per cancellarla completamente da qualunque pagina. Mi sbaglio e non ho controllato bene o il tema proprio non supporta lo spostamento?
Thanks

**Comment by jimo** [comment]
Il tema non supporta la visualizzazione della slideshow su pagine specifiche.
Per farlo devi:
- aprire il file `lib\slider.php`
- all'interno della funzione `init` inserisci (riga 140) `( is_page(ID_DELLA_PAGINA) ) ||`, e al posto di ID_DELLA_PAGINA metti l'id della pagina che preferisci

**Comment by franccicccio** [comment]
wow grazie hai una soluzione per tutto, proverò anche questa non appena il mio sito rotto torna agibile

**Comment by franccicccio** [comment]
allora ho trovato che l'id della pagina in cui vorrei mettere la slide, è 888, ma non ne sono sicuro. Mi ha dato questo numero un plugin che uso per altre cose. Ad ogni modo la funzione è diventata:

```
}


// the slider init
function init(){

    if ( shiword_get_opt( 'shiword_sticky' ) && !is_404() ) {
        if (
            ( is_page(888) && shiword_get_opt( 'shiword_sticky_pages' ) ) ||
            ( is_single() && shiword_get_opt( 'shiword_sticky_posts' ) ) ||
            ( is_front_page() && shiword_get_opt( 'shiword_sticky_front' ) ) ||
            ( ( is_archive() || is_search() ) && shiword_get_opt( 'shiword_sticky_over' ) )
        ) $this->the_slider(); 
    }

}
```

Il problema è che la slide non mi compare!! Dove potrei aver sbagliato?

**Comment by franccicccio** [comment]
ok ho risolto! Sono andato nelle "Opzioni Tema" di Shiword e alla sezione slideshow ho vistato la casella "nelle pagine", che tempo fa avevo svistato perchè la slide mi compariva in TUTTE le pagine! :/ Thanks!

**Comment by jimo** [comment]
Forse mi ero spiegato male, non dovevi inserire l'ID in is_page(), ma aggiungere proprio una nuova riga col codice che ti avevo dato. Comunque no problema, anche così funziona. ;)

Solved -> Closed
