### ISSUE TITLE
when posting to facebook, no image

### ISSUE THREAD

**Issue by violablu** [TwoBeers/shiword#49]
I am using this theme on 2 wordpress accounts, and on both when you share a post on facbook, no image shows. I have found the only way around it is to change to a new theme, add my post, then change back to your theme, and then share...it is a weird problem....but any post created with this theme has no picture on facebook.

**Comment by jimo** [comment]
That's really weird. The theme doesn't affect the post editing in any way. What do you use for sharing a post?

**Comment by jimo** [comment]
No reply -> closed
