### ISSUE TITLE
Shiword + WP 3.9.1: Lo sfondo non ha più immagini!

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#50]
...e così ho messo un colore monocromatico. 
Anche così il tema non è malaccio, ma con un minimo di fantasia sullo sfondo era molto più bello.
Cmq, andando nella sezione sfondi del tema, non compaiono più neppure le opzioni di scelta delle foto/sfondi. Non è che ci sono e queste non funzionano, non ci sono proprio! Spero che con futuri aggiornamenti questo vizio possa risolversi.

**Comment by ilmaren** [comment]
shiword che versione?
la 4.03 non da problemi con WP 3.9.1, se è una versione precedente, è possibile ci siano incompatibilità

**Comment by franccicccio** [comment]
beh ho la versione nuova, ho deattivato tutti i plugin ed ancora lo sfondo non mi è tornato. Forse dovrei anche disinstallarli uno ad uno. Uff. Cmq ad oggi mi sto tenendo lo sfondo grigio sperando che con futuri aggiornamenti lo sfondo miracolosamente riappaia :/

**Comment by jimo** [comment]
Se non sbaglio dovrebbe esserci un'opzione che si chiama "sfondo potenziato" o qualcosa del genere. Controlla che sia attiva

**Comment by franccicccio** [comment]
Ho trovato l'opzione "sfondo personalizzato", ed era vistato. Siccome però sotto c'era una nota: "utilizza la pagina avanzata per lo sfondo personalizzato, anzichè quella normale. Disabilitala se lo sfondo personalizzato si comporta stranamente", io l'ho disabilitata.
Tornando alla opzione sfondo, non è cambiato un granchè. Posso cambiare benissimo solo i colori, le immagini personalizzate caricate dal pc non le prende, mentre il paniere shiword standard di immagini non è più disponibile.
In ogni caso ho disattivato tutti i plugin e la situazione non è cambiata.
Credo allora che dovrei proprio disinstallarli uno ad uno e vedere passo passo. Farò questo quando avrò imparato a fare una copia in locale del sito, o quando avrò imparato a clonarlo da qualche altra parte. Al momento non mi va di mettere a rischio lo status quo per questo "dettaglio", è stato logorante aver a che fare con l'amministrazione aruba qualche mese fa...

**Comment by jimo** [comment]
Boh, a questo punto immagino ci sia qualche altro problema. Forse con il prossimo aggiornamento (che per ora nn è ancora stato messo in cantiere) si risolverà
