### ISSUE TITLE
Widget Shiword "Seguimi": aggiungere nuovo link di nuovo network

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#51]
La opzione di scelta offerta da questa widget è vasta. Però vorrei mettere un link a una pagina di un piccolo network che nessuno conosce, potrei farlo? 
Ho notato che potrei facilmente aggiungere il link personale, ma poi l'icona è già preimpostata e così anche l'alttributo che compare scorrendo sopra l'icona. Dovrei cambiare solo queste due ultime cose... perciò penso che dovrei andare nell'Editor di WP, ma dove esattamente?

**Comment by jimo** [comment]
Allora, tenendo conto che hai la v4.03:
- apri il file lib/widgets.php con l'editor
- alla riga 620 troverai la lista dei servizi supportati
- inserisci una nuova riga (dove vuoi all'interno dell'array) tipo

```
'slug_del_mio_network' => 'Nome del mio Network',
```
- vai ora nella cartella images/follow e carica (tipo con un programma ftp) un'immagine **PNG** che si chimami **slug_del_mio_network.png**,  possibilmente quadrata e 60x60 (ma non è strettamente necessario)

il nuovo campo per inserire il link dovrebbe adesso comparire nel form del widget

E' un po' complicato, lo so, ma in versioni future sarà più semplice aggiungere i network usando dei filtri
