### ISSUE TITLE
Immagine della Testata: non si rimpicciolisce!

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#52]
Salve, cliccando sul menù "Personalizza" di wordpress, la cornice di shiword si restringe e si compatta a lato destro dello schermo, perchè in quello sinistro c'è un menù. Tutto ok. Tutte le funzioni fondamentali si restringono proporzionalmente di conseguenza, tranne l'immagine della testata! 
Non vi avevo fatto caso prima perchè ne utilizzavo una a motivo ciclico, ora invece ho messo una immagine mia personale di 850pixel per 150pixel, con sopra una bella frase. 
Ecco andando su "personalizza" ed avendo modo di osservare l'effetto di restringimento di shiword, ho visto che è tutto perfetto, tranne quella frase, che adesso compare a metà. Ho perso pure la parte sinistra dell'immagine in cui avevo disegnato un'icona speciale.
Ora, sul mio pc coi vari brower il sito mi compare sempre perfettamente, ma non vorrei che negli schermi più piccoli perdessi pezzi. E' brutta quella frase a metà e sarebbe bello si rimpicciolisse anch'essa. Dico questo anche perchè so che shiword è ottimizzato per i tablet/cellulari, e questo forse potrebbe essere un difetto. Non che il mio sito ancora in gestazione sia fatto per i cellulari, ma non si sa mai in futuro!

**Comment by jimo** [comment]
E' una limitazione già nota e che è presente in un altro nostro tema che stiamo attualmente aggiornando. Quando/se aggiorneremo shiword, il problema verrà sistemato. Purtroppo la modifica è troppo complessa per fornire un fix veloce

**Comment by franccicccio** [comment]
va bene no problem!
