### ISSUE TITLE
Ingrandire le immagini

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#53]
Sin dall'inizio notai che su SHIWORD cliccando su un'immagine era possibile ingrandirla con un pregevole effetto di finestra dentro un'altra finestra richiudibile con un click. Devo ammettere che fu una delle cose che mi fece innamorare di questo tema, bello anche però su molti altri punti.
Con l'aggioranmento di WP a 4.0 mi sembra di aver capito che questa opzione spuntata o non spuntata nel pannello di amministrazione non funziona più. Le ho provate tutte. Ma questo effetto di ingrandimento "nidificato" delle immagini, come si chiama esattamente? Forse tickbox?

**Comment by jimo** [comment]
Shiword utilizza una libreria js che si chiama Thickbox. Nel nostro test server (con WP4.0.1 e Shiword4.03) tutto funziona regolarmente. Nel caso prova con il modulo [Carousel di Jetpack](http://jetpack.me/support/carousel/). L'aspetto e la funzionalità è molto simile

**Comment by franccicccio** [comment]
Quindi in pratica se svisto o non svisto l'opzione Thickbox non c'entra niente con quel piacevole effetto di apertura delle immagini dentro una finestra chiudibile con un clic? E se non è attiva dipende da qualche altra opzione che ho accidentalmente svistato o un plugin che ha disattivato il meccanismo. Giusto?

**Comment by jimo** [comment]
L'opzione Thickbox è proprio quel effetto di apertura delle immagini. Cmq si, è così, se nn funziona è perchè dipende da altre opzioni ("animazioni javascript" se non sbaglio)
![thickboxdep](https://cloud.githubusercontent.com/assets/454482/6628866/4a706f72-c909-11e4-8fd3-cc6568fbc728.png)
o perchè stai utilizzando il Carousel di Jetpack.
Se non vuoi comunque le animazioni js, installa Jetpack e attiva il modulo Carousel

**Comment by franccicccio** [comment]
Ciao scusa non ho capito bene: non ho installato il plugin Carousel di Jetpack.
Dovrei installarlo ed attivare Carousel per avere l'effetto Thickbox?
Visto che Thickbox richiede le animazioni js, c'è un modo per attivarle anche senza plugin Jetpack-Carousel?

**Comment by jimo** [comment]
Scusami, forse mi sono spiegato male.
"Thickbox" e "animazioni javascript" sono due opzioni del tema.
Il modulo "Carousel" fa parte del plugin Jetpack, che col tema non c'entra nulla.

Se la funzionalità Thickbox non funziona ci possono essere 3 motivi:
1. l'opzione Thickbox è disattivata
2. l'opzione "animazioni javascript" è disattivata. in questo caso l'opzione Thickbox è sempre disattivata automaticamente.
3. il plugin Jetpack è installato e la funzione Carousel è attivata. in questo caso la funzione Thickbox è rimpiazzata dal Carousel.

Quindi se vuoi usare la funzionalità Thickbox, devi attivare sia la rispettiva opzione sia l'opzione "animazioni javascript".

Se per qualche motivo vuoi mantenere disattivata l'opzione "animazioni javascript", niente Thickbox. In alternativa puoi usare Carousel di Jp, che è molto simile (ma più completo)

**Comment by franccicccio** [comment]
grazie mille, spiegazione chiarissima :) 
ora vedo come attivare le animazioni javascript visto che l'opzione thickbox è spuntata.

**Comment by franccicccio** [comment]
perfetto, adesso il Thickbox funziona a dovere grazie ancora!
