### ISSUE TITLE
Gruppi di gruppi [OT]

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#54]
Ciao Buddypress offre l'opportunità di creare gruppi, ma io avrei l'esigenza di riunire questi gruppi in gruppi più grandi, e questi più grandi in altri ancora più grandi (4 sub-livelli in totale). 
Lo so che non c'entra nulla con SHIWORD ma non ho trovato qui su Github i link per messaggistica privata e neppure su twobeer.net ed avrei bisogno solo di un parere semplice da chi bazzica da abbastanza tempo nel mondo dello php.
Quindi, considerando che non appena finisco con il mio lavoro millenario dovrò aihme cominciare quello di studio dello php perchè non posso chiedere consulenze per spostare ogni virgola (ad es. diversificare il tasto "crea gruppo" dagli altri, con un diverso colore od effetto tridimensionale o togliere il link al RSS e spostarlo da un'altra parte), pensate che creare un plugin per creare gruppi di gruppi su BP sia un'impresa possibile per un neofita, oppure occorre un programmatore navigato, diciamo con 10 anni di esperienza? 
Grazie per il parere!
Inoltre avrei bisogno anche di fare un tema per prestashop che sono tutti a pagamento attualmente e sono anche caotici!

**Comment by jimo** [comment]
Dico solo che se dovessi farlo io... non lo farei. Ho avuto modo di spulciare un po' il codice di buddypress e sinceramente una modifica del genere è decisamente troppo complicata. Potresti chiedere direttamente al forum di supporto di bp, magari c'è già qualcuno che si è cimentato nell'impresa

**Comment by jimo** [comment]
tra l'altro, alle volte non è necessario essere dei guru di php e smontare codici per modificare piccole cose, come i tasti di bp. Sono sicuro che ogni tasto ha una classe html, quindi con un minimo di codice css si riescono a fare un bel po' di modifiche

**Comment by jimo** [comment]
che poi basterebbe cercare...
https://wordpress.org/plugins/bp-group-hierarchy/

**Comment by franccicccio** [comment]
ahaha grazie mille tempo fa cercai sulla barra google "groups of groups" a volte devi azzeccare la parola, in questo caso subgroups! Cmq il plugin è compatibile fino alla versione WP 3.8 ma siccome presto diventerò un mago del php avendo già la base miracolosamente fatta sarà un colpo riablitarla per la 4.0 e successive! Mah...si... certo... speriamo.

**Comment by jimo** [comment]
ma sicuro che non funziona con WP4.0? Certe volte sono solamente testati con versioni vecchie ma funzionano benissimo anche con versioni più recenti

**Comment by franccicccio** [comment]
mmm ora provo e ti dico

**Comment by franccicccio** [comment]
funziona! Ma il css è tutto da sistemare ed alcune funzioni da ristrutturare :/ vabbè la base cmq è fatta meglio che partire da zero :) 
Ascolta ti ho risposto anche sul Caroseul del Thickbox nell'altro post [immagini da ingrandire] ma essendo chiuso non vorrei che ti sfuggisse!
