### ISSUE TITLE
I 4 - 1 = 3 tasti della bacheca buddypress

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#55]
Nel pannello principale della bacheca buddypress ci sono 4 voci-tasti che dovrebbero selezionare i flussi di commenti del sito:

Tutti gli utenti - I miei gruppi - I miei preferiti - Menzioni

Anche se a queste voci c'è un link di descrizione che compare passandoci sopra col mouse, penso sia più efficace metterci delle icone.
Non credo avrò problemi a trovare delle icone allegre e colorate, il dilemma è come sostituirle alle frasette. Pensate che questa sia cosa che io possa fare facilmente?  
Inoltre DESIDERO TOGLIERE LA VOCE "TUTTI GLI UTENTI" perchè non è che interessa a tutti farsi gli affari di tutti gli altri. Pensate che possa manomettere così drammaticamente il tema WP-BP con le mie attuali capacità prossime allo zero?
Grazie mille!

Francesco

**Comment by jimo** [comment]
Come ti ho già detto da qualche altra parte, è molto probabile che queste modifiche si riescano a fare senza nessun codice php, basta aggiungere qualche modifica css e il gioco è (dovrebbe essere) fatto

**Comment by jimo** [comment]
ad esempio, il tasto "tutti gli utenti" ha id="activity-all"
scrivi qualcosa del genere:

```
#activity-all { display: none }
```

e il tasto è sparito

**Comment by franccicccio** [comment]
:) ma questa è magia! 
Grazie per la considerazione, diventerò bravissimo anche con lo css :dart:

**Comment by jimo** [comment]
Il css è moooooolto più semplice da imparare. Anche perchè è quasi impossibile fare danni, a differenza di php ;)
