### ISSUE TITLE
Shiword & Prestashop

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#56]
...cercando un tema prestashop e non piacendomene nessuno pur anche di 129.99 euro, mi è venuta una idea "mostruosa". Ma non è che shiword sia adattababile a prestashop? Dopotutto sono scritti entrambi in php... Studiando ed applicandomi potrei partorire questo mostro genetico oppure è proprio impossibile per principio adattare l'aspetto shiword al core prestashop piuttosto che al core wordpress?
Facendo una stima a caso qualora sapessi programmare in php, ci vorrebbero mesi o anni di lavoro?

**Comment by jimo** [comment]
Ahahahaah il mostro genetico! :D
Comunque sono convinto che l'impostazione grafica di shiword (come di qualunque altro tema wp) sia adattabile. Da quel che ho visto su Prestashop, puoi crearti la struttura delle pagine un po' come vuoi, quindi basterebbe utilizzare una struttura simile a quella che genera il tema per wp, ed applicargli lo stile originale.
Non saprei dirti quanto tempo potrebbe servire, sicuramente non anni ;)

**Comment by franccicccio** [comment]
oh grazie fai sembrare la cosa semplice allora procedo a farmi questo benedetto corso che missà è diventato una necessità :/

**Comment by jimo** [comment]
eh non so, anche perchè a Prestashop ho dato un occhiata velocissima

(issue closed)
