### ISSUE TITLE
Shiword & Moodle. Guida urgente

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#58]
Ciao scusate ancora il semi off-topic, ma mi piacerebbe forzare il tema shiword per adattarsi a Moodle, così che il sito sembri unico anche se effettivamente retto da un triplice ragionamento php (wordpress, prestashop e moodle).
Ora soldi non ne ho e non posso pagare 1.000-2.000 euro agli sviluppatori giacchè lo scopo finale è racimolare soldi non dare soldi ad altri, inoltre sarebbe bene che capissi qualcosa delle tecnologia su cui smanetto, e pertanto mi serve una guida urgente per studiare e riuscire nell'impresa.
La prima impresa è piegare shiword alle esigenze prestashop e moodle, solo dal punto di vista della grafica.
Ho fatto una ricerca su internet e i libri sono veramente tanti, apparetnemente tutti buoni, a me me ne serve solo uno, con cui cominciare. Se mi dite titolo ed autore obbedisco e compro quanto prima. Intanto guardo su amazon... cerco "programmazione php"

**Comment by franccicccio** [comment]
cmq ho desistito da quest'intenzione acrobatica, mi scelgo uno dei tempi che su moodle al contrario di Prestashop sono più numerosi (gratis)

**Comment by jimo** [comment]
Ciao, scusa del mostruso ritardo nelle risposte ma siamo un po' impegnati, quindi....
Ad ogni modo la mia risposta in questo caso sarebbe stata abbastanza inutile in quanto non saprei proprio che libro suggerirti. Io non ne ho usati, ma consulto regolarmante http://www.php.net/manual/en/index.php

(chiudo la issue)
