### ISSUE TITLE
Fare le tabelle in html

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#59]
Salve, mi sono trito e ritrito per aumentare il padding delle celle/tabelle. 
Ho trovato il tag `<table  cellpadding="19" cellspacing="1">` ma alla fine mi è venuto un dubbio: forse Shiword non ammette variazioni del padding nelle "sue" tabelle? :/
E' possibile?

**Comment by jimo** [comment]
Tranquillo, puoi variare quello che vuoi.
Ma non usare `cellpadding` o `cellspacing`, per fortuna col css si può fare tutto senza agire sul codice html!
http://www.w3schools.com/html/html_tables.asp
http://www.w3schools.com/tags/tag_table.asp
http://www.w3schools.com/css/css_table.asp

**Comment by franccicccio** [comment]
ah non sapevo che il css "copre" l'html, grazie per i link ora me li segno
