### ISSUE TITLE
Anteprima di stampa

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#60]
Salve, la pagina "anteprima di stampa" con l'anteprima dell'articolo è molto pulita e bella. E' una funzione che sto rivalutando per vari problemi. Cmq ho visto che l'anteprima riporta non solo l'articolo, ma anche le cose che ci sono nel widget articoli, quindi 6 elementi nel mio caso :/
La cosa è intenzionale?
Si potrebbe togliere, magari nelle future versioni di shiword, che non so se ci saranno ma mai dire mai? 
Grazie

**Comment by jimo** [comment]
Si si, è intenzionale, ma ci sono pro e contro nel mantenerla visibile nella stampa.
Ovviamente puoi eliminarla con un po' di css.
Nel file css/print.css aggiungi alla fine

```
#single-widget-area {
    display: none;
}
```

**Comment by jimo** [comment]
ps: stiamo lavorando ad una nuova versione di shiword, ma non ti so dire se vedrà mai la luce ;)

**Comment by franccicccio** [comment]
vabbè il lavoro già fatto è buono, se ci sono i consigli pronti per aggiustare alcune piccole cose alla fine ... può fermarsi a questa versione. Tanto il tema non necessita di aggiornamenti con gli aggiornamenti di wordpress come un qualsiasi plugin, no?

**Comment by franccicccio** [comment]
eccetto il rimpicciolimento dell'immagine di testata, quello dovrebbe essere fatto :/

**Comment by jimo** [comment]
Purtroppo anche i temi possono aver bisogno di update con l'andar del tempo (e di wp)
