### ISSUE TITLE
Elemento nel footer

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#61]
Salve, avrei l'esigenza di mettere una piccolissima icona di 32 pixdel con link ad una pagina del sito, in uno dei due angoli in basso della cornice di shiword, dove c'è scritto: "benvenuto, oggi è [data]".
E' possibile? 
Grazie mille!

**Comment by jimo** [comment]
Tutto è possibile!
Nel file quickbar.php, riga 209, all'interno della "statusbar"

Piccolissimo suggerimento:
In genere non è complicato trovare la posizione del codice da modificare.
Praticamente tutti i moderni browsers hanno il proprio strumento per analizzare le pagine, quindi è piuttosto facile individuare l'id o la classe di un dato elemento (dasto dx -> ispeziona elemento -> ta-dahh!)
Una volta che hai queste informazioni, ti basta fare una ricerca nei file .php del tema per scoprire dove l'elemento viene creato.
Credimi, è un metodo che di solito non richiede più di un minuto

**Comment by franccicccio** [comment]
...non avendo infarinatura di base, lo schermo è un mistero impenetrabile; anche la semplice "ricerca nei file .php del tema" sembra una cosa complicata. Dovrò copiare tutti i fogli della struttura del sito in notepad, immagino, per manipolare "da casa" il tutto e fare le ricerche, no?
Cmq il tempo di comprare il primo libro di linguaggi di programmazione e forse ci capiremo al volo! Nel frattempo grazie davvero per le indicazioni superprecise!! Cercherò di usare di più il "ispeziona elemento"
