### ISSUE TITLE
Jetpack Share buttons moved in new version

### ISSUE THREAD

**Issue by Altersoundwork** [TwoBeers/shiword#62]
Hi,

First of all thank you for a great theme and your time reading this.

I recently updated from 3.x to 4.x and noticed the Jetpack social share buttons have been moved to the top of the post.

To make sure it wasn't a jetpack update thing, I reverted to the previous version of the theme and noticed the buttons where after the post content as they where so it's definately something in the newest theme version.

Could you let me know how to move them to where they where before? (After the content but before the comments).

Cheers

**Comment by jimo** [comment]
Hi, thanks for using our theme! 
Yes, you're right, the sharing links are moved at top of the post.
If you prefer the previous behavior, you need to modify the code
Open the file lib/plugins.php and remove the lines 37->42

```
        //Sharedaddy
        if ( function_exists( 'sharing_display' ) ) {
            remove_filter(  'the_content',                  'sharing_display', 19 );
            remove_filter(  'the_excerpt',                  'sharing_display', 19 );
            add_filter(     'shiword_like_it',              'sharing_display', 19 );
        }
```
