### ISSUE TITLE
Shiword in puro php

### ISSUE THREAD

**Issue by franccicccio** [TwoBeers/shiword#63]
Hello, per diversi motivi mi sono convertito a ProcessWire da Wordpress. Cioè ci sto provando studiando i tutorial. 
ProcessWire costruisce il suo template usando totalmente il linguaggio php, perciò mi chiedevo se sarebbe possibile in linea di principio riprodurre il bellissimo Shiword tramite php. Naturalmente per le immagini di rifinitura rimane html, css, ma tutta la struttura fondamentale sarebbe in php. 
Che dite, potrei ottenere un effetto uguale a quello che ottengo con wordpress?

**Comment by jimo** [comment]
Ovviamente! Anche WordPress è scritto interamente in php, compresi i temi.

**Comment by franccicccio** [comment]
ah perfetto allora devo solo "tradurre" il pack vedremo...
